spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/samples-reactive-api

logging:
  level:
    root: info
    org.lab: debug

management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always
